### ISSUE TITLE
Buggy data leads to 500 error

### ISSUE THREAD

**Issue by jamespfennell** [jamespfennell/transiter#39]
Stack trace:

```
Unexpected exception in processing HTTP request.
Traceback (most recent call last):
  File "/home/james/transiter/git/transiter/transiter/http/httpmanager.py", line 169, in _perform_request
    response = func(*args, **kwargs)
  File "/home/james/transiter/git/transiter/transiter/http/endpoints/stopendpoints.py", line 118, in get_in_system_by_id
    return stopservice.get_in_system_by_id(system_id, stop_id)
  File "</home/james/transiter/.pyenv/lib/python3.6/site-packages/decorator.py:decorator-gen-31>", line 2, in get_in_system_by_id
  File "/home/james/transiter/git/transiter/transiter/data/dbconnection.py", line 85, in unit_of_work
    result = func(*args, **kw)
  File "/home/james/transiter/git/transiter/transiter/services/stopservice.py", line 95, in get_in_system_by_id
    if stop_event_filter.exclude(trip_stop_time, direction_name):
  File "/home/james/transiter/git/transiter/transiter/services/stopservice.py", line 370, in exclude
    this_time = trip_stop_time.arrival_time.timestamp()
AttributeError: 'NoneType' object has no attribute 'timestamp'
Unexpected exception in processing HTTP request.
Traceback (most recent call last):
  File "/home/james/transiter/git/transiter/transiter/http/httpmanager.py", line 169, in _perform_request
    response = func(*args, **kwargs)
  File "/home/james/transiter/git/transiter/transiter/http/endpoints/stopendpoints.py", line 118, in get_in_system_by_id
    return stopservice.get_in_system_by_id(system_id, stop_id)
  File "</home/james/transiter/.pyenv/lib/python3.6/site-packages/decorator.py:decorator-gen-31>", line 2, in get_in_system_by_id
  File "/home/james/transiter/git/transiter/transiter/data/dbconnection.py", line 85, in unit_of_work
    result = func(*args, **kw)
  File "/home/james/transiter/git/transiter/transiter/services/stopservice.py", line 95, in get_in_system_by_id
    if stop_event_filter.exclude(trip_stop_time, direction_name):
  File "/home/james/transiter/git/transiter/transiter/services/stopservice.py", line 370, in exclude
    this_time = trip_stop_time.arrival_time.timestamp()
AttributeError: 'NoneType' object has no attribute 'timestamp'
```

**Comment by jamespfennell** [comment]
I don't know what this is about
